steps:
  - id: buildDockerImage
    name: "gcr.io/cloud-builders/docker"
    entrypoint: bash
    args:
      - "-c"
      - "-e"
      - |
        _BRANCH_IMAGE_TAG=$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9]/-/g')
        docker build \
        --label org.opencontainers.image.revision=${COMMIT_SHA} \
        --label org.opencontainers.image.source=github.com/viki-org/agent-chat-ui \
        -t ${_REGISTRY}/${_IMAGE_NAME}:${SHORT_SHA} \
        -t ${_REGISTRY}/${_IMAGE_NAME}:$${_BRANCH_IMAGE_TAG} \
        -t asia.${_REGISTRY}/${_IMAGE_NAME}:${SHORT_SHA} \
        -t asia.${_REGISTRY}/${_IMAGE_NAME}:$${_BRANCH_IMAGE_TAG} \
        .

  - id: triggerSpinnaker
    waitFor: ['buildDockerImage']
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        [[ "$BRANCH_NAME" == "$_DEPLOYABLE_BRANCH" ]] || exit 0 &&  \
        gcloud pubsub topics publish spinnaker-webhook \
          --project "spinnaker-205804" \
          --message "{
            \"pubsub_secret\":\"gophercon\",
            \"application\":\"ops-gpt-ui\",
            \"artifact\": {
              \"type\":\"docker/image\",
              \"name\":\"${_ASIA_REGISTRY}/${_IMAGE_NAME}\",
              \"version\":\"${SHORT_SHA}\"
            },
            \"parameters\": {
              \"staging_only\": \"$${STAGING_ONLY}\"
            }
          }"

images:
  - ${_ASIA_REGISTRY}/${_IMAGE_NAME}
  - ${_REGISTRY}/${_IMAGE_NAME}

substitutions:
  _REGISTRY: "gcr.io/viki-images"
  _ASIA_REGISTRY: "asia.gcr.io/viki-images"
  _IMAGE_NAME: agent-chat-ui
  _DEPLOYABLE_BRANCH: main

timeout: 3600s
